package contactsPro;
import java.io.*;
/**
*
* @author Omer Farooq Ahmed, Maaz Hassan, Tabish Muzaffar
*/
public class NewContactGUI extends javax.swing.JFrame {

   /**
    * Creates new form NewContactGUI
    */
   public NewContactGUI() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jLabel2 = new javax.swing.JLabel();
       jLabel4 = new javax.swing.JLabel();
       jLabel6 = new javax.swing.JLabel();
       jLabel8 = new javax.swing.JLabel();
       jLabel10 = new javax.swing.JLabel();
       jLabel12 = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       jLabel1 = new javax.swing.JLabel();
       jLabel3 = new javax.swing.JLabel();
       jTextField1 = new javax.swing.JTextField();
       jTextField2 = new javax.swing.JTextField();
       jTextField3 = new javax.swing.JTextField();
       jTextField4 = new javax.swing.JTextField();
       jTextField5 = new javax.swing.JTextField();
       jTextField6 = new javax.swing.JTextField();
       jTextField7 = new javax.swing.JTextField();
       jTextField8 = new javax.swing.JTextField();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jPanel1.setBackground(new java.awt.Color(255, 255, 255));

       jLabel2.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel2.setText("Primary Phone");

       jLabel4.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel4.setText("Secondary Phone");

       jLabel6.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel6.setText("Primary Email");

       jLabel8.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel8.setText("Secondary Email");

       jLabel10.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel10.setText("Address");

       jLabel12.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel12.setText("Date of Birth");

       jButton1.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jButton1.setText("Save");

       jLabel1.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel1.setText("First Name ");

       jLabel3.setFont(new java.awt.Font("Simplifica", 0, 24)); // NOI18N
       jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel3.setText("Last Name");

       jTextField1.setText("");

       jTextField2.setText("");

       jTextField3.setText("");
       jTextField3.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField3ActionPerformed(evt);
           }
       });

       jTextField4.setText("");
       jTextField4.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField4ActionPerformed(evt);
           }
       });

       jTextField5.setText("");
       jTextField5.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField5ActionPerformed(evt);
           }
       });

       jTextField6.setText("");
       jTextField6.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField6ActionPerformed(evt);
           }
       });

       jTextField7.setText("");
       jTextField7.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField7ActionPerformed(evt);
           }
       });

       jTextField8.setText("");
       jTextField8.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jTextField8ActionPerformed(evt);
           }
       });
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(18, 18, 18)
                       .addComponent(jTextField1))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(18, 18, 18)
                       .addComponent(jTextField2))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(18, 18, 18)
                       .addComponent(jTextField3))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jTextField4))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(10, 10, 10)
                       .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                               .addGap(10, 10, 10)
                               .addComponent(jTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
                           .addGroup(jPanel1Layout.createSequentialGroup()
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                               .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(jPanel1Layout.createSequentialGroup()
                               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                               .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)))))
               .addContainerGap())
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addGap(18, 18, 18)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(12, 12, 12)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGap(9, 9, 9)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jLabel4)
                   .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addGap(18, 18, 18)
                       .addComponent(jLabel8)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                       .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(0, 0, Short.MAX_VALUE)))
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );

       pack();
   }// </editor-fold>                        

   private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }                                           

   private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {                                            
       // TODO add your handling code here:
   }
   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
	   //SAVE BUTTON code
	   ContactDetails cd= new ContactDetails(jTextField1.getText(), jTextField2.getText(), jTextField3.getText(), jTextField4.getText()
			   ,jTextField5.getText(), jTextField6.getText(), jTextField7.getText(), jTextField8.getText());
	   ContactsListGUI.phoneTrie.Insert(jTextField3.getText(), cd);
	   ContactsListGUI.fNameTrie.Insert(jTextField1.getText(), cd);
	   ContactsListGUI.lNameTrie.Insert(jTextField2.getText(), cd);
	   
	   //Displaying the new contact on the JList immediately
	   DisplayNumber();
	   //Serializing the new phoneTrie
	   try {
		   ObjectOutputStream out= new ObjectOutputStream(new FileOutputStream("trie3.ser"));
		   out.writeObject(ContactsListGUI.phoneTrie);
		   out.close();
	   }
	   catch (IOException e) {
		   e.printStackTrace();
	   }
	   //Serializing the new fNameTrie
	   try {
		   ObjectOutputStream out2= new ObjectOutputStream(new FileOutputStream("trie.ser"));
		   out2.writeObject(ContactsListGUI.fNameTrie);
		   out2.close();
	   }
	   catch (IOException e) {
		   e.printStackTrace();
	   }
	   //Serializing the new lNameTrie
	   try {
		   ObjectOutputStream out3= new ObjectOutputStream(new FileOutputStream("trie2.ser"));
		   out3.writeObject(ContactsListGUI.lNameTrie);
		   out3.close();
	   }
	   catch (IOException e) {
		   e.printStackTrace();
	   }
   } 

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(NewContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(NewContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(NewContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(NewContactGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new NewContactGUI().setVisible(true);
           }
       });
   }
   
	public void DisplayNumber(){
	    ToDisplayNumber(ContactsListGUI.phoneTrie.rootNumber);
	}
	public NodeNumber ToDisplayNumber(NodeNumber rootN){

//	    for(int i = 0; i < 1; i++){
	        
	        if(rootN.zero != null){
	        ToDisplayNumber(rootN.zero);
	        }
	        
	        if(rootN.i != null){
	        ToDisplayNumber(rootN.i);
	        }
	        
	        if(rootN.ii != null){
	        ToDisplayNumber(rootN.ii);
	        }
	        
	        if(rootN.iii != null){
	        ToDisplayNumber(rootN.iii);
	        }
	        
	        if(rootN.iv != null){
	        ToDisplayNumber(rootN.iv);
	        }
	        
	        if(rootN.v != null){
	        ToDisplayNumber(rootN.v);
	        }
	        
	        if(rootN.vi != null){
	        ToDisplayNumber(rootN.vi);
	        }
	        
	        if(rootN.vii != null){
	        ToDisplayNumber(rootN.vii);
	        } 
	        
	        if(rootN.viii != null){
	        ToDisplayNumber(rootN.viii);
	        } 
	        
	        if(rootN.ix != null){
	        ToDisplayNumber(rootN.ix);
	        }        
	        
	        if(rootN.end == true && rootN.ContactD.PNumber.equals(jTextField3.getText())){
	        	ContactsListGUI.listNames.addElement(rootN.ContactD.FName+" "+rootN.ContactD.LName+": "+rootN.ContactD.PNumber);
	        	//rootN.ContactD.printNumber();
	        }
	        else{
	        }
	  //  }
	return rootN;
	}

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTextField jTextField1;
   private javax.swing.JTextField jTextField2;
   private javax.swing.JTextField jTextField3;
   private javax.swing.JTextField jTextField4;
   private javax.swing.JTextField jTextField5;
   private javax.swing.JTextField jTextField6;
   private javax.swing.JTextField jTextField7;
   private javax.swing.JTextField jTextField8;
   // End of variables declaration                   
}

