package contactsPro;
import javax.swing.*;
/**
*
* @author Omer Farooq, Maaz Hassan, Tabish Muzaffar
*/
public class SearchResultsGUI extends javax.swing.JFrame {

   /**
    * Creates new form SearchResultsGUI
    */
	//Static variable for jlist entries 
	public static DefaultListModel listResults= new DefaultListModel();
   public SearchResultsGUI() {
       initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       jPanel1 = new javax.swing.JPanel();
       jScrollPane1 = new javax.swing.JScrollPane();
       jList1 = new javax.swing.JList<String>(listResults);
       jLabel1 = new javax.swing.JLabel();
       jLabel2 = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       jButton2 = new javax.swing.JButton();

       setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

       jPanel1.setBackground(new java.awt.Color(255, 255, 255));

       jScrollPane1.setViewportView(jList1);

       jLabel1.setIcon(new javax.swing.ImageIcon("Images/contactsPro.png")); // NOI18N

       jLabel2.setBackground(new java.awt.Color(204, 204, 255));
       jLabel2.setFont(new java.awt.Font("Simplifica", 0, 36)); // NOI18N
       jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
       jLabel2.setText("Search Results");

       jButton1.setIcon(new javax.swing.ImageIcon("Images/view contact.png")); // NOI18N
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       jButton2.setIcon(new javax.swing.ImageIcon("Images/delete.png")); // NOI18N
       jButton2.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton2ActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
       jPanel1.setLayout(jPanel1Layout);
       jPanel1Layout.setHorizontalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                   .addGroup(jPanel1Layout.createSequentialGroup()
                       .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addGap(0, 0, Short.MAX_VALUE)))
               .addContainerGap())
       );
       jPanel1Layout.setVerticalGroup(
           jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(jPanel1Layout.createSequentialGroup()
               .addContainerGap()
               .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                   .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addContainerGap())
       );

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
       getContentPane().setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
       );

       pack();
   }// </editor-fold>                        

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
	   //VIEW CONTACT BUTTON
	   int temp2=-1;
	   String temp=jList1.getSelectedValue();
   		for (int i=0; i<temp.length(); i++) {
   			if (temp.charAt(i)==('0')) {
   				temp2=i;
   				break;
   			}
   		}
   		//getting the number from the jlist
   		String temp3=temp.substring(temp2, temp.length());
   		//using the number we got search for the contact details and display them on a new viewContacts()
   		this.SearchNumber(temp3);
   		ViewContactGUI newWindow= new ViewContactGUI(searchContactFName, searchContactLName, searchContactPhone1, searchContactPhone2, searchContactEmail1, searchContactEmail2, searchContactDOB, searchContactAddress);
   		newWindow.setVisible(true);
   }                                        

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
       /* Set the Nimbus look and feel */
       //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
       /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
       try {
           for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               if ("Nimbus".equals(info.getName())) {
                   javax.swing.UIManager.setLookAndFeel(info.getClassName());
                   break;
               }
           }
       } catch (ClassNotFoundException ex) {
           java.util.logging.Logger.getLogger(SearchResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (InstantiationException ex) {
           java.util.logging.Logger.getLogger(SearchResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (IllegalAccessException ex) {
           java.util.logging.Logger.getLogger(SearchResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       } catch (javax.swing.UnsupportedLookAndFeelException ex) {
           java.util.logging.Logger.getLogger(SearchResultsGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
       }
       //</editor-fold>

       /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
               new SearchResultsGUI().setVisible(true);
           }
       });
   }
   public void SearchNumber(String Number){
   	int t = 0;
   	NodeNumber temp;
   	temp = ContactsListGUI.phoneTrie.rootNumber; 
   	//Goes into this recursive function to fetch value. 
   	temp = ToSearchNumber(ContactsListGUI.phoneTrie.rootNumber, Number, t);

   	}

   public NodeNumber ToSearchNumber(NodeNumber rootN, String name, int strV ){
   	    
   	    char c = 0; //to Store each letter of string.
   	    NodeNumber temp; 
   	    
   	    if(strV < name.length()){ //itrates through string and stores letter in 'c' after each recursive call. 
   	    c = name.charAt(strV);
   	    strV++;
   	    }
   	    else{ //checks once we have reached the end of the string if the boolean/marker is true then the word is present else no. 
   	        if(rootN.end == true){
   	             System.out.println("We found the Query you were looking for!");
   	             //rootN.ContactD.print();
   	             searchContactFName=rootN.ContactD.FName;
   	             searchContactLName=rootN.ContactD.LName;
   	             searchContactPhone1=rootN.ContactD.PNumber;
   	             searchContactPhone2=rootN.ContactD.PNumber2;
   	             searchContactEmail1=rootN.ContactD.Email;
   	             searchContactEmail2=rootN.ContactD.Email2;
   	             searchContactDOB=rootN.ContactD.DOB;
   	             searchContactAddress=rootN.ContactD.Address;
   	             ContactsListGUI.phoneTrie.SearchValueNumber = rootN; //this is for the delete function. 
   	        }
   	        else{
   	            System.out.println("Your search yeilded no results");        
   	        }
   	    }
   	    //Sequentially goes through all the letter ifs.
   	    if(c == '0'){
   	        if(rootN.zero != null){
   	        temp = ToSearchNumber(rootN.zero, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }
   	    }
   	    else if(c == '1'){
   	        if(rootN.i != null){
   	        temp = ToSearchNumber(rootN.i, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }
   	    else if(c == '2'){
   	        if(rootN.ii != null){
   	        temp = ToSearchNumber(rootN.ii, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }
   	    else if(c == '3'){
   	        if(rootN.iii != null){
   	        temp = ToSearchNumber(rootN.iii, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }
   	    else if(c == '4'){
   	        if(rootN.iv != null){
   	        temp = ToSearchNumber(rootN.iv, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }
   	    else if(c == '5'){
   	        if(rootN.v != null){
   	        temp = ToSearchNumber(rootN.v, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }
   	    else if(c == '6'){
   	        if(rootN.vi != null){
   	        temp = ToSearchNumber(rootN.vi, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }
   	    else if(c == '7'){
   	        if(rootN.vii != null){
   	        temp = ToSearchNumber(rootN.vii, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }
   	    else if(c == '8'){
   	        if(rootN.viii != null){
   	        temp = ToSearchNumber(rootN.viii, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }    
   	    else if(c == '9'){
   	        if(rootN.ix != null){
   	        temp = ToSearchNumber(rootN.ix, name, strV);
   	        }
   	        else{
   	        System.out.println("Your search yeilded no results");        
   	        }        
   	    }
   	    else{
   	    }
   	return rootN;     
   	}
   

   // Variables declaration - do not modify                     
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JList<String> jList1;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JScrollPane jScrollPane1;
   public static String searchContactFName, searchContactLName, searchContactPhone1, searchContactPhone2, searchContactEmail1, searchContactEmail2, searchContactDOB, searchContactAddress;

   // End of variables declaration                   
}
